variables:
  subscriptionID: 'your subscription ID'
  tenantId: 'your tenet ID'
  environment: 'dev'
  azureSubscription: 'your service connection'
  resourceGroupName: 'your Rg name'
  location: 'East Asia'
  keyVaultName: 'your Kv name'
  vnetAddressSpace: '10.0.0.0/16'
  subnetAddressSpaceSQLMI: '10.0.0.0/24'
  subnetAddressSpacePrivateEndpoint: '10.0.1.0/24'
  adminObjectId: 'Your AAD admin object ID'
  skuName: 'GP_Gen5'
  skuTier: 'GeneralPurpose'
  skuFamily: 'Gen5'
  skuCapacity: 16
