variables:
  subscriptionID: 'your subscription ID'
  tenantId: 'Your Tenet ID'
  environment: 'prd'
  azureSubscription: 'Your service Connection Name'
  resourceGroupName: 'Your RG Name'
  location: 'West Europe'
  keyVaultName: 'Your KV name'
  vnetAddressSpace: '10.100.33.0/24'
  subnetAddressSpaceSQLMI: '10.100.34.0/26'
  subnetAddressSpacePrivateEndpoint: '10.100.35.0/26'
  adminObjectId: 'Your AAD Admin Object ID'
  skuName: 'GP_PremiumSeries'
  skuTier: 'GeneralPurpose'
  skuFamily: 'PremiumSeries'
  skuCapacity: 32
